prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix : <https://purl.org/prozion/food_industry#>

select distinct ?factory ?place ?product where {
  {
    ?factory rdf:type :ProductionUnit .
    ?factory :prod ?product .
    ?product :broader* :Продукт_молочный .
  }
  optional
  {
    ?factory :place ?place .
  }}
